<?php

namespace WCS\HackathonNoelBundle\Repository;

/**
 * ChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildRepository extends \Doctrine\ORM\EntityRepository
{
}
